version: '3.4'

x-main: &main
  tty: true
  stdin_open: true
  build: .
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    REDIS_URL: redis://redis:6379/
    FOODA_USERNAME:
    FOODA_PASSWORD:
    SLACK_CHANNEL_TO_POST_TO:
    FOOD_BUDGET: 6
  volumes:
    - '.:/usr/src/app'
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: 'postgres:11.2-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *main
    command: sidekiq

  web:
    <<: *main
    command: web
    ports:
      - '3000:3000'

volumes:
  redis:
  postgres:
