version: '3.4'

x-main: &main
  tty: true
  stdin_open: true
  build: .
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    REDIS_URL: redis://redis:6379/
    FOODA_USERNAME:
    FOODA_PASSWORD:
    SLACK_CHANNEL_TO_POST_TO:
    FOOD_BUDGET: 6
    HISTFILE: /root/.bash_history
  volumes:
    - '.:/app:cached'
    - ".docker/.pryrc:/root/.pryrc:ro"
    - "bash_history:/root/.bash_history"
    - "psql_history:/root/.psql_history"
    - "irb_history:/root/.irb_history"
  tmpfs:
    - /tmp
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - './log:/var/log/psql_history'

  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  sidekiq:
    <<: *main
    command: sidekiq

  web:
    <<: *main
    command: web
    ports:
      - '3000:3000'

volumes:
  redis:
  postgres:
  bash_history:
  psql_history:
  irb_history:
